apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: kbit-api-pipeline-by-order
spec:
  resources:
    - name: kbit-git
      type: git
    - name: kbit-api-image
      type: image
  tasks:
    - name: unit-tests
      taskRef:
        name: springboot-mvn-unittests
      resources:
        inputs:
          - name: workspace
            resource: kbit-git
    - name: sonarqube-scan
      taskRef:
        name: sonarqube-scan
      runAfter:
        - unit-tests
      resources:
        inputs:
          - name: workspace
            resource: kbit-git
    - name: s2i-build
      taskRef:
        kind: ClusterTask
        name: s2i-java-11
      runAfter:
        - sonarqube-scan
      resources:
        inputs:
          - name: source
            resource: kbit-git
        outputs:
          - name: image
            resource: kbit-api-image
    - name: integration-tests
      retries: 2
      taskRef:
        name: integration-tests
      params:
        - name: appName
          value: "kbit-api"
        - name: pgName
          value: "pg-kbit-api"
      resources:
        inputs:
          - name: workspace
            resource: kbit-git
          - name: image
            resource: kbit-api-image
            from:
              - s2i-build
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: kbit-api-pipeline-run-by-order
spec:
  pipelineRef:
    name: kbit-api-pipeline-by-order
  resources:
    - name: kbit-git
      resourceRef:
        name: kbit-git
    - name: kbit-api-image
      resourceRef:
        name: kbit-api-image