apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kbit-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/Dimss/kbit-api
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kbit-api-image
spec:
  type: image
  params:
    - name: url
      value: docker.io/dimssss/kbit-api:latest