apiVersion: v1
kind: ServiceAccount
metadata:
  name: oc-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: oc-client
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oc-client
subjects:
- kind: ServiceAccount
  name: oc-client
roleRef:
  kind: Role
  name: oc-client
  apiGroup: rbac.authorization.k8s.io
