apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-interceptor
spec:
  serviceAccountName: tekton-triggers
  triggers:
    - name: kbit-api-trigger
      binding:
        name: pipeline-binding
      template:
        name: pipeline-template