apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers
rules:
  # Permissions for every EventListener deployment to function
  - apiGroups: ["tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates", "tasks", "taskruns"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"] # secrets are only needed for Github/Gitlab interceptors
    verbs: ["get", "list", "watch"]
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers
subjects:
  - kind: ServiceAccount
    name: tekton-triggers
roleRef:
  kind: Role
  name: tekton-triggers
  apiGroup: rbac.authorization.k8s.io