apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: report-nginx
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: report-nginx
    weight: 100
status:
  ingress:
   - conditions: